"""Orchestrator agent.

Drives the 4-agent HazardMind pipeline end to end:

    satellite -> hazard -> impact -> report -> complete

It connects to the Band room with the SDK's Anthropic adapter (agent_id /
api_key come from agent_config.yaml), kicks the pipeline off by mentioning the
satellite agent, and then watches the room transcript to advance the DB status
as each agent reports completion.

Messaging is natural-language first. Every handoff is sent as TWO Band
messages (see band_client.send_handoff):
  - a natural message generated by Featherless that reads like an expert
    colleague in a real emergency (visible to judges in the Band chat), and
  - a structured JSON event carrying the same data (parsed by the pipeline).

The orchestrator also actively cross-validates each agent's output and opens a
discussion in the room when something looks off (extent vs GDACS, low
confidence, CRITICAL risk, missing zones, multiple disasters).

Pipeline messages all carry the event_id, and each agent announces it is done
with a line like "satellite complete" / "hazard complete" / ... — that marker
is what monitor_progress() keys off of to step the database forward.
"""
import asyncio
import json
import logging
import os

from dotenv import load_dotenv

from band_client import (
    AGENT_PERSONALITIES,
    HAZARD_HANDLE,
    IMPACT_HANDLE,
    REPORT_HANDLE,
    SATELLITE_HANDLE,
    all_handles_text,
    generate_natural_message,
    handoff_message,
    inbound_store,
    mentions_for,
    mentions_for_all,
    notify_satellite,
    poll_room_into_store,
    send_event,
    send_handoff,
    send_task_update,
    send_text_message,
    send_thought,
)
from db import insert_satellite_result, update_event_status

load_dotenv()

logger = logging.getLogger("hazardmind.orchestrator")

BAND_WS_URL = os.getenv("THENVOI_WS_URL", "wss://app.band.ai/api/v1/socket/websocket")
BAND_REST_URL = os.getenv("THENVOI_REST_URL", "https://app.band.ai/").rstrip("/")
ANTHROPIC_MODEL = os.getenv("ORCHESTRATOR_MODEL", "claude-sonnet-4-5-20250929")

ORCHESTRATOR_AGENT_KEY = "orchestrator_agent"
ORCHESTRATOR_ROLE = "Pipeline Coordinator"
ORCHESTRATOR_AGENT = "hazardmind-orchestrator"

# How often monitor_progress() re-reads the Band room while waiting.
POLL_INTERVAL_SECONDS = 5
# No hard timeout — the satellite pipeline can take a long time for real imagery.
# monitor_progress() waits indefinitely until each agent posts completion.
DISCUSSION_WAIT_SECONDS = 30

# While waiting on a real agent, if the room stays quiet for this long the
# orchestrator nudges the agent ONCE for a status update. Kept infrequent and
# capped (MAX_NUDGES) so nudges don't pile into the agent's own work queue and
# slow it down. It NEVER advances the pipeline off a nudge — only a genuine
# completion signal from the agent moves the stage forward.
NUDGE_AFTER_SECONDS = 45
MAX_NUDGES = 2

# Cross-validation thresholds.
GDACS_EXTENT_MULTIPLIER = 2.0   # satellite extent > GDACS estimate * this -> flag
LOW_CONFIDENCE = 0.7            # confidence below this -> warn the team
CRITICAL_AREA_KM2 = 200.0       # affected area above this -> critical handoff
MIN_SATELLITE_ZONES = 5        # fewer zones than this with HIGH risk -> flag

# Pipeline handoff plan, keyed off each agent's completion marker.
#   agent             -> the agent whose completion triggers this transition
#   status, step      -> the (status, step) the event moves INTO
#   next_handle       -> Band handle to hand the job to (None at the end)
#   next_agent        -> bare name of the receiving agent (for personality)
#   next_role         -> human role of the receiving agent
#   task_name         -> task whose completion we announce
PIPELINE_TRANSITIONS = [
    {
        "agent": "satellite",
        "status": "processing",
        "step": "hazard",
        "next_handle": HAZARD_HANDLE,
        "next_agent": "hazardmind-hazard",
        "next_role": "Hazard Assessment Lead",
        "task_name": "Satellite",
    },
    {
        "agent": "hazard",
        "status": "processing",
        "step": "impact",
        "next_handle": IMPACT_HANDLE,
        "next_agent": "hazardmind-impact",
        "next_role": "Impact Analyst",
        "task_name": "Hazard",
    },
    {
        "agent": "impact",
        "status": "processing",
        "step": "report",
        "next_handle": REPORT_HANDLE,
        "next_agent": "hazardmind-report",
        "next_role": "Reporting Officer",
        "task_name": "Impact",
    },
    {
        "agent": "report",
        "status": "complete",
        "step": "complete",
        "next_handle": None,
        "next_agent": None,
        "next_role": None,
        "task_name": "Report",
    },
]


def _record_only(base_cls):
    """Wrap any Band ``SimpleAdapter`` subclass into a RECORD-ONLY adapter.

    Band delivers room messages to the connected SDK agent over its WebSocket
    execution loop (the REST GET /messages history is empty for this agent), so
    we capture each inbound message into the shared inbound_store. That store is
    what monitor_progress() and GET /band-log read from.

    Crucially, the returned adapter is RECORD-ONLY: it deliberately skips
    ``super().on_event()`` (the call that runs the underlying LLM tool loop and
    posts a reply). The orchestrator's real messages — dispatch, cross-validation
    discussions, nudges, handoffs, the closing summary — are all sent explicitly
    via band_client REST posts from start_pipeline()/monitor_progress(). Letting
    the LLM also auto-reply to every @mention created an endless chatter loop
    with the satellite agent (each reply @mentioned the other, which triggered
    another reply) and spawned phantom event_ids. The orchestrator only speaks
    when the pipeline logic decides to — i.e. while a stage is incomplete, or on
    an anomaly/discrepancy — never idle chatter once an agent is done.

    ``on_event`` is the SimpleAdapter entry point that fans out to ``on_message``
    (the LLM call), so overriding it record-only suppresses auto-reply for ANY
    base adapter — Gemini, Anthropic, or LangGraph alike.
    """

    class RecordingAdapter(base_cls):  # type: ignore[valid-type, misc]
        async def on_event(self, inp) -> None:  # type: ignore[override]
            try:
                msg = inp.msg
                inbound_store.add(
                    {
                        "id": getattr(msg, "id", None),
                        "content": getattr(msg, "content", ""),
                        "type": getattr(msg, "message_type", "text"),
                        "sender": {
                            "id": getattr(msg, "sender_id", None),
                            "name": getattr(msg, "sender_name", None),
                        },
                        "created_at": str(getattr(msg, "created_at", "") or ""),
                    }
                )
            except Exception:  # noqa: BLE001 - recording must not break delivery
                logger.exception("Failed to record inbound Band message")
            # Intentionally do NOT call super().on_event(inp): the orchestrator
            # does not converse via the LLM, it drives the pipeline explicitly.

    return RecordingAdapter


def get_best_adapter():
    """Pick the best available Band adapter, record-only, by priority.

    All three options are wrapped record-only (see ``_record_only``) so the
    orchestrator never auto-replies via the LLM regardless of which backend
    serves the per-turn model. Priority:

      1. Gemini 3.5 Flash      — if GEMINI_API_KEY is set.
      2. Claude Sonnet 4.6     — via AIML's Anthropic endpoint (ANTHROPIC_*).
      3. Featherless Kimi K2.6 — LangGraph adapter over the OpenAI protocol.

    Returns the constructed adapter. Featherless is the always-available tail
    (it matches what every pipeline agent already runs), so this never returns
    None as long as FEATHERLESS_API_KEY is configured.
    """
    # Priority 1: Gemini.
    gemini_key = os.getenv("GEMINI_API_KEY")
    if gemini_key:
        try:
            from band.adapters.gemini import GeminiAdapter

            adapter = _record_only(GeminiAdapter)(
                model=os.getenv("GEMINI_MODEL", "gemini-3.5-flash"),
                api_key=gemini_key,
            )
            logger.info("Orchestrator adapter: Gemini 3.5 Flash")
            return adapter
        except Exception:  # noqa: BLE001 - fall through to the next provider
            logger.exception("Gemini adapter unavailable, falling back")

    # Priority 2: Claude (Anthropic protocol via AIML).
    anthropic_key = os.getenv("ANTHROPIC_API_KEY")
    if anthropic_key:
        try:
            from band.adapters import AnthropicAdapter

            adapter = _record_only(AnthropicAdapter)(model=ANTHROPIC_MODEL)
            logger.info("Orchestrator adapter: %s", ANTHROPIC_MODEL)
            return adapter
        except Exception:  # noqa: BLE001 - fall through to Featherless
            logger.exception("Claude adapter unavailable, falling back")

    # Priority 3: Featherless via LangGraph (always-available tail).
    from band.adapters.langgraph import LangGraphAdapter
    from langchain_openai import ChatOpenAI

    llm = ChatOpenAI(
        model=os.getenv("FEATHERLESS_MODEL", "moonshotai/Kimi-K2.6"),
        api_key=os.getenv("FEATHERLESS_API_KEY"),
        base_url=os.getenv("FEATHERLESS_BASE_URL", "https://api.featherless.ai/v1"),
    )
    adapter = _record_only(LangGraphAdapter)(llm=llm)
    logger.info("Orchestrator adapter: Featherless Kimi K2.6")
    return adapter


class OrchestratorAgent:
    """Coordinates the disaster-analysis pipeline over a Band room."""

    def __init__(self) -> None:
        self.agent = None
        self.connected = False
        # Per-event context so handoffs can reference earlier findings.
        self._context: dict[str, dict] = {}

    async def connect(self) -> None:
        """Connect to the Band room using a recording Anthropic adapter.

        agent_id and api_key are loaded from agent_config.yaml under the
        ``orchestrator_agent`` key.
        """
        from band import Agent

        adapter = get_best_adapter()
        self.agent = Agent.from_config(
            ORCHESTRATOR_AGENT_KEY,
            adapter=adapter,
            ws_url=BAND_WS_URL,
            rest_url=BAND_REST_URL,
        )
        await self.agent.start()
        self.connected = True
        logger.info("Orchestrator connected")

    # -- helpers --------------------------------------------------------------

    def _room(self, event_id: str) -> str | None:
        """Return the dynamic Band room id for this event, if one was set.

        start_pipeline() stores the per-event room on self._context so the
        deeper helpers (cross-validation _say, broadcasts) post to the same
        room without threading room_id through every signature. Falls back to
        None, which band_client resolves to the static BAND_ROOM_ID.
        """
        return self._context.get(event_id, {}).get("room_id")

    async def _say(
        self,
        receiver_agent: str,
        receiver_handle: str,
        receiver_role: str,
        context,
        findings,
        urgency: str = "normal",
        anomalies=None,
        questions=None,
        event_id: str | None = None,
        room_id: str | None = None,
    ) -> str:
        """Generate + post a natural orchestrator message to one agent.

        When `event_id` is given it is appended to the message body (so the post
        is scoped to the event) AND used to resolve the event's Band room.
        `room_id` lets a caller route the post to the event's room WITHOUT
        appending the event_id line — used by cross-validation discussion
        messages, whose body is left as-is for the existing tests.
        """
        msg = await generate_natural_message(
            sender_agent=ORCHESTRATOR_AGENT,
            sender_role=ORCHESTRATOR_ROLE,
            receiver_agent=receiver_agent,
            receiver_handle=receiver_handle,
            context=context,
            findings=findings,
            urgency=urgency,
            anomalies=anomalies or [],
            questions=questions or [],
            personality=AGENT_PERSONALITIES[ORCHESTRATOR_AGENT],
        )
        if event_id:
            msg = f"{msg}\nevent_id: {event_id}"
        target_room = room_id or (self._room(event_id) if event_id else None)
        await send_text_message(
            msg,
            mentions=mentions_for(receiver_handle),
            room_id=target_room,
        )
        return msg

    def _agent_data(self, event_id: str, agent: str) -> dict:
        """Return the structured result payload an agent reported, if any.

        Solution 3: this must work for EVERY agent (hazard/impact/report), not
        just satellite — otherwise the orchestrator forwards an empty ``{}`` to
        the next stage and the receiving LLM hallucinates from nothing. We look,
        in order, for:
          1. a nested ``data.data`` block tagged for this agent,
          2. a flat ``data`` block tagged for this agent,
          3. the agent's own result JSON appended to its room message tail
             (the standard "<prose> --- <json>" handoff format).
        Only messages FROM the agent are considered (orchestrator echoes skipped).
        """
        for parsed in inbound_store.for_event(event_id):
            if self._is_own_message(parsed):
                continue
            data = parsed.get("data") or {}
            if str(data.get("step", "")).lower() == agent and data.get("data"):
                inner = data.get("data")
                if isinstance(inner, dict):
                    return inner
            if str(data.get("step", "")).lower() == agent and isinstance(data, dict):
                return data
        # Fall back to the flat completion JSON the agent appends to its message
        # tail — generalised to all agents (was satellite-only).
        return self._agent_payload(event_id, agent)

    @staticmethod
    def _agent_payload(event_id: str, agent: str) -> dict:
        """Pull an agent's result JSON off its room message tail.

        Each agent relays a natural message and appends its full result object
        (with event_id + status=complete). We scan the recorded inbound messages
        — ignoring the orchestrator's own — for that JSON. Handles the wrapper
        shapes agents use: a flat object, a ``{"hazard": {...}}`` / ``{"data":
        {...}}`` nested block, etc., returning the most useful inner dict.
        """
        for parsed in inbound_store.for_event(event_id):
            if OrchestratorAgent._is_own_message(parsed):
                continue
            obj = _json_object_from_text(str(parsed.get("content", "")))
            if not isinstance(obj, dict):
                continue
            if str(obj.get("event_id", "")) != event_id:
                continue
            if str(obj.get("status", "")).lower() not in ("complete", ""):
                continue
            # The payload must come FROM this agent. Without this check the
            # satellite's completion JSON (which carries a generic `data` block)
            # was returned as hazard/impact/report output — so the orchestrator
            # forwarded the satellite payload down the chain and downstream agents
            # "analysed" satellite data as if it were the prior stage's result.
            tag = str(obj.get("from") or obj.get("agent") or obj.get("step") or "").lower()
            if tag not in (agent, f"hazardmind-{agent}"):
                continue
            # Unwrap a per-agent result block when present (hazard nests under
            # "hazard", others under "data"); else use the flat object.
            for key in (agent, "data", "result"):
                inner = obj.get(key)
                if isinstance(inner, dict) and inner:
                    return inner
            return obj
        return {}

    @staticmethod
    def _satellite_payload(event_id: str) -> dict:
        """Back-compat alias — satellite result JSON off its message tail."""
        return OrchestratorAgent._agent_payload(event_id, "satellite")

    async def _persist_satellite(self, event_id: str, data: dict) -> None:
        """Write the satellite result row from its completion payload."""
        if not data:
            logger.info(
                "event_id=%s: no structured satellite payload to persist", event_id
            )
            return
        try:
            await insert_satellite_result(event_id=event_id, data=data)
            logger.info("event_id=%s: satellite_results written", event_id)
        except Exception:  # noqa: BLE001 - DB write must not break the pipeline
            logger.exception(
                "event_id=%s: failed to write satellite_results", event_id
            )

    # -- pipeline -------------------------------------------------------------

    async def start_pipeline(
        self, event_id: str, disaster_data: dict, room_id: str | None = None
    ) -> None:
        """Move the event into satellite processing and hand it to Agent 1.

        room_id is the dynamic Band room created for this event (router.py).
        It is stored on self._context and threaded through every post so the
        whole pipeline conversation stays in that one room; when None, posts
        fall back to the static BAND_ROOM_ID.
        """
        disaster_type = disaster_data.get("disaster_type")
        location = disaster_data.get("location")
        magnitude = disaster_data.get("magnitude") or 0

        self._context[event_id] = {"disaster": disaster_data, "room_id": room_id}

        # Reasoning thought (kept text-searchable for the existing test).
        await send_thought(
            f"New disaster event received: {disaster_type} in {location}. "
            "Orchestrator analyzing incoming disaster report before dispatching "
            "the satellite team.",
            room_id=room_id,
        )
        await send_task_update("Pipeline", "started", room_id=room_id)

        await update_event_status(event_id, status="processing", step="satellite")
        await send_task_update("Satellite", "processing", room_id=room_id)

        # ONE dispatch message to the satellite: natural prose (judges read this)
        # then a `---` line and the structured fields the agent parses. A single
        # clean chat line — not two near-identical messages — so the satellite's
        # work queue and the transcript stay uncluttered.
        urgency = "high" if (magnitude or 0) > 5 else "normal"
        try:
            natural = await generate_natural_message(
                sender_agent=ORCHESTRATOR_AGENT,
                sender_role=ORCHESTRATOR_ROLE,
                receiver_agent="hazardmind-satellite",
                receiver_handle=SATELLITE_HANDLE,
                context=disaster_data,
                findings=(
                    f"New {disaster_type} emergency dispatched for {location}"
                    + (f", magnitude {magnitude}" if magnitude else "")
                ),
                urgency=urgency,
                questions=["Please prioritize satellite coverage of the urban core."],
                personality=AGENT_PERSONALITIES[ORCHESTRATOR_AGENT],
            )
        except Exception:  # noqa: BLE001 - natural msg is best-effort
            logger.exception("event_id=%s: natural dispatch failed", event_id)
            natural = (
                f"{SATELLITE_HANDLE} New {disaster_type} emergency in {location}. "
                "Please begin satellite analysis."
            )
        fields = [
            f"event_id: {event_id}",
            f"location: {location}",
            f"disaster_type: {disaster_type}",
        ]
        if magnitude:
            fields.append(f"magnitude: {magnitude}")
        dispatch = f"{natural}\n\n---\n" + "\n".join(fields)
        await send_text_message(
            dispatch, mentions=mentions_for(SATELLITE_HANDLE), room_id=room_id
        )

        logger.info("Pipeline started for event_id=%s", event_id)

    async def monitor_progress(self, event_id: str, room_id: str | None = None) -> str:
        """Watch the Band room and advance the DB as each agent completes.

        On every poll cycle we first fetch the full room transcript via the
        Band REST API (poll_room_into_store) to seed inbound_store with
        messages from agents that address other participants (e.g. satellite
        posting to @hazardmind-hazard). Without this, the orchestrator's
        WebSocket adapter only sees messages directed *at itself*, and misses
        completions from pipeline agents.

        There is no hard timeout — the satellite pipeline can take several
        minutes for real imagery downloads. We poll indefinitely until each
        agent posts its completion signal. The pipeline is NEVER advanced off a
        nudge or a guess — only a genuine completion signal from the agent moves
        a stage forward.
        """
        # Keep the per-event room authoritative on context (start_pipeline
        # normally sets it; honor an explicit room_id here too).
        if room_id is not None:
            self._context.setdefault(event_id, {})["room_id"] = room_id
        room_id = self._room(event_id)

        stage = 0

        while stage < len(PIPELINE_TRANSITIONS):
            t = PIPELINE_TRANSITIONS[stage]
            agent = t["agent"]

            # Pull the full room transcript into inbound_store so we can see
            # completions from agents that didn't @mention the orchestrator.
            await poll_room_into_store(event_id, room_id=room_id)

            # Advance on a room completion signal OR on the agent's DB row. Band's
            # REST history is empty for per-event rooms, so hazard/impact/report
            # often can't post a detectable room signal — but they DO write their
            # DB rows via the deterministic autodispatch. Treating the DB row as a
            # completion lets the orchestrator advance (and @mention the next
            # agent in chat) instead of stalling at "satellite -> hazard".
            if await self._agent_completed(event_id, agent) or await self._agent_completed_in_db(event_id, agent):
                await self._advance(event_id, t)
                stage += 1
                continue

            # An agent that gives up (e.g. a sustained internet outage exceeded
            # the download grace budget) posts an error/failed signal instead of
            # a completion. Detect it and abort the pipeline cleanly — mark the
            # event failed rather than waiting forever for a completion that will
            # never come.
            err = await self._agent_failed(event_id, agent)
            if err:
                await self.handle_failure(event_id, agent, err)
                logger.error("event_id=%s: pipeline failed at %s: %s", event_id, agent, err)
                return "failed"

            await self._wait_with_nudge(event_id, agent)

        await self.on_pipeline_complete(event_id)
        logger.info("event_id=%s: pipeline complete", event_id)
        return "complete"

    async def _wait_with_nudge(self, event_id: str, agent: str) -> None:
        """Sleep one poll cycle; nudge the agent if the room has gone quiet.

        Keeps the room alive while a real agent (the satellite) is grinding
        through a long job: if no new message referencing this event has
        appeared for NUDGE_AFTER_SECONDS, the orchestrator asks the agent for a
        status update. This NEVER advances the pipeline — only the agent's real
        completion signal does that.
        """
        await asyncio.sleep(POLL_INTERVAL_SECONDS)

        seen = len(inbound_store.for_event(event_id))
        last = self._context.setdefault(event_id, {})
        if seen != last.get("_last_seen_count"):
            # Activity since we last looked — reset the quiet timer.
            last["_last_seen_count"] = seen
            last["_quiet_seconds"] = 0
            return

        last["_quiet_seconds"] = last.get("_quiet_seconds", 0) + POLL_INTERVAL_SECONDS
        nudges = last.get("_nudge_count", 0)
        if last["_quiet_seconds"] >= NUDGE_AFTER_SECONDS and nudges < MAX_NUDGES:
            last["_quiet_seconds"] = 0
            last["_nudge_count"] = nudges + 1
            handle = SATELLITE_HANDLE if agent == "satellite" else HAZARD_HANDLE
            role = "Satellite Imagery Lead" if agent == "satellite" else "Pipeline Agent"
            try:
                await self._say(
                    f"hazardmind-{agent}",
                    handle,
                    role,
                    context={"event_id": event_id},
                    findings="Checking in on your progress",
                    urgency="normal",
                    questions=[
                        "What's your current status? Still processing the imagery, "
                        "or do you need anything from the team?"
                    ],
                    event_id=event_id,
                )
            except Exception:  # noqa: BLE001 - nudge is best-effort
                logger.exception("event_id=%s: nudge to %s failed", event_id, agent)

    async def _advance(self, event_id: str, transition: dict) -> None:
        """Apply one pipeline transition: cross-validate, DB update, handoff."""
        agent = transition["agent"]
        data = self._agent_data(event_id, agent)

        # Reset the per-stage nudge budget/timer so the next agent starts fresh.
        ctx = self._context.setdefault(event_id, {})
        ctx["_nudge_count"] = 0
        ctx["_quiet_seconds"] = 0

        # Persist the satellite agent's result so GET /results can join it
        # (the satellite agent reports over Band; it does not write the DB).
        if agent == "satellite":
            await self._persist_satellite(event_id, data)

        room_id = self._room(event_id)
        await update_event_status(
            event_id, status=transition["status"], step=transition["step"]
        )
        await send_task_update(transition["task_name"], "complete", room_id=room_id)
        logger.info(
            "event_id=%s: %s complete -> %s/%s",
            event_id,
            agent,
            transition["status"],
            transition["step"],
        )

        # Cross-validate this agent's output and discuss anomalies in the room.
        anomalies, questions, urgency = await self.cross_validate_and_discuss(
            event_id, agent, data
        )

        next_handle = transition["next_handle"]
        if next_handle is None:
            return

        await send_task_update(
            transition["step"].capitalize(), "processing", room_id=room_id
        )
        await self._handoff(event_id, transition, data, anomalies, questions, urgency)

    async def _handoff(
        self,
        event_id: str,
        transition: dict,
        data: dict,
        anomalies: list,
        questions: list,
        urgency: str,
    ) -> None:
        """Generate a natural handoff + structured event for the next agent."""
        agent = transition["agent"]
        disaster = self._context.get(event_id, {}).get("disaster", {})
        findings = self._summarize_findings(agent, data) or (
            f"{agent} stage complete"
        )
        try:
            natural = await generate_natural_message(
                sender_agent=ORCHESTRATOR_AGENT,
                sender_role=ORCHESTRATOR_ROLE,
                receiver_agent=transition["next_agent"],
                receiver_handle=transition["next_handle"],
                context={"disaster": disaster, f"{agent}_result": data},
                findings=findings,
                urgency=urgency,
                anomalies=anomalies,
                questions=questions,
                personality=AGENT_PERSONALITIES[ORCHESTRATOR_AGENT],
            )
        except Exception:  # noqa: BLE001
            logger.exception("event_id=%s: handoff generation failed", event_id)
            content, _ = handoff_message(transition["next_handle"], event_id)
            natural = content

        structured = {
            "event_id": event_id,
            "from": agent,
            "to": transition["next_agent"],
            "data": data,
            "anomalies": anomalies,
        }
        await send_handoff(
            natural,
            structured,
            mentions=mentions_for(transition["next_handle"]),
            room_id=self._room(event_id),
        )

    @staticmethod
    def _summarize_findings(agent: str, data: dict) -> str:
        """Turn an agent's structured result into a short findings sentence."""
        if not data:
            return ""
        if agent == "satellite":
            zones = data.get("zones") or data.get("zone_count")
            area = data.get("affected_area_km2")
            cities = data.get("risk_cities") or []
            bits = []
            if zones is not None:
                bits.append(f"{zones} flood zones identified")
            if area is not None:
                bits.append(f"covering {area} km²")
            if cities:
                bits.append(f"affected cities: {', '.join(map(str, cities))}")
            return "Satellite sweep complete — " + ", ".join(bits) if bits else ""
        if agent == "hazard":
            level = data.get("risk_level")
            depth = data.get("flood_depth")
            bits = []
            if level:
                bits.append(f"flood classified {level}")
            if depth:
                bits.append(f"flood depth {depth}")
            return "Hazard assessment complete — " + ", ".join(bits) if bits else ""
        if agent == "impact":
            pop = data.get("total_affected")
            hosp = data.get("hospitals_at_risk")
            roads = data.get("roads_blocked")
            bits = []
            if pop is not None:
                bits.append(f"{pop} people in affected zones")
            if hosp is not None:
                bits.append(f"{hosp} hospitals at risk")
            if roads is not None:
                bits.append(f"{roads} roads blocked")
            return "Impact numbers are in — " + ", ".join(bits) if bits else ""
        return ""

    # -- cross-validation / discussion ---------------------------------------

    async def cross_validate_and_discuss(
        self, event_id: str, agent: str, data: dict
    ) -> tuple[list, list, str]:
        """Inspect an agent's output and open a Band discussion on anomalies.

        Returns (anomalies, questions, urgency) to carry into the next handoff.
        Discussion triggers:
          1. satellite extent > GDACS estimate * 2  -> ask satellite to recheck
          2. confidence < 0.7                        -> warn the team
          3. risk_level CRITICAL                     -> @all prioritize speed
          4. HIGH risk but few satellite zones       -> ask satellite to investigate
          5. multiple disasters detected             -> ask team to prioritize
        """
        anomalies: list[str] = []
        questions: list[str] = []
        urgency = "high"

        if agent == "satellite":
            area = _num(data.get("affected_area_km2"))
            zones = _num(data.get("zones") or data.get("zone_count"))
            gdacs = _num(data.get("gdacs_estimate_km2"))
            confidence = _num(data.get("confidence"))

            # Trigger 1: extent far larger than GDACS estimate.
            if area and gdacs and area > gdacs * GDACS_EXTENT_MULTIPLIER:
                ratio = round(area / gdacs, 1)
                anomalies.append(
                    f"Satellite extent {ratio}x larger than GDACS estimate "
                    f"({area} km² vs {gdacs} km²)"
                )
                questions.append("Sensor anomaly or genuine secondary flooding?")
                await self._say(
                    "hazardmind-satellite",
                    SATELLITE_HANDLE,
                    "Satellite Imagery Lead",
                    context=data,
                    findings=(
                        f"Your flood extent ({area} km²) is {ratio}x larger "
                        f"than the GDACS estimate ({gdacs} km²)"
                    ),
                    urgency="high",
                    questions=[
                        "Sensor anomaly or genuine secondary flooding? "
                        "Please verify the affected coordinates."
                    ],
                    room_id=self._room(event_id),
                )
                await asyncio.sleep(DISCUSSION_WAIT_SECONDS)

            # Trigger 2: low confidence.
            if confidence is not None and confidence < LOW_CONFIDENCE:
                anomalies.append(
                    f"Low satellite confidence ({confidence}) — treat extent as provisional"
                )
                await self._say(
                    "hazardmind-satellite",
                    SATELLITE_HANDLE,
                    "Satellite Imagery Lead",
                    context=data,
                    findings=(
                        f"Confidence on this sweep is only {confidence}. "
                        "Flagging uncertainty to the team"
                    ),
                    urgency="high",
                    questions=["Can you re-run classification to tighten confidence?"],
                    room_id=self._room(event_id),
                )

            # Trigger 4: GDACS shows risk but satellite found no zones.
            if zones == 0 and gdacs and gdacs > 0:
                anomalies.append("No satellite zones but GDACS shows risk")
                await self._say(
                    "hazardmind-satellite",
                    SATELLITE_HANDLE,
                    "Satellite Imagery Lead",
                    context=data,
                    findings="GDACS shows active risk but your sweep returned zero zones",
                    urgency="high",
                    questions=["Please investigate — possible cloud cover or missed pass?"],
                    room_id=self._room(event_id),
                )

        if agent == "hazard":
            level = str(data.get("risk_level", "")).upper()
            sat = self._agent_data(event_id, "satellite")
            sat_zones = _num(sat.get("zones") or sat.get("zone_count"))

            # Trigger 3: CRITICAL risk -> alert everyone.
            if level == "CRITICAL":
                urgency = "critical"
                await send_text_message(
                    f"{all_handles_text()} CRITICAL event confirmed. "
                    "All agents prioritize speed.",
                    mentions=mentions_for_all(),
                    room_id=self._room(event_id),
                )
            # Trigger 4b: HIGH risk but few satellite zones.
            if level == "HIGH" and sat_zones is not None and sat_zones < MIN_SATELLITE_ZONES:
                anomalies.append(
                    f"Risk HIGH but only {sat_zones} satellite zones — discrepancy"
                )
                await self._say(
                    "hazardmind-hazard",
                    HAZARD_HANDLE,
                    "Hazard Assessment Lead",
                    context={"hazard": data, "satellite_zones": sat_zones},
                    findings=(
                        f"Risk assessed HIGH but satellite only mapped {sat_zones} "
                        "zones — flagging the discrepancy"
                    ),
                    urgency="high",
                    questions=["Can you reconcile risk level against the mapped extent?"],
                    room_id=self._room(event_id),
                )

        # Trigger 5: multiple disasters detected (any agent may report this).
        disasters = data.get("disasters") or data.get("detected_disasters")
        if isinstance(disasters, list) and len(disasters) > 1:
            anomalies.append(f"Multiple disasters detected ({len(disasters)})")
            await self._say(
                "hazardmind-satellite",
                SATELLITE_HANDLE,
                "Satellite Imagery Lead",
                context={"disasters": disasters},
                findings=f"{len(disasters)} concurrent disasters detected",
                urgency="high",
                questions=["Team, which event should we prioritize first?"],
                room_id=self._room(event_id),
            )

        # Carry CRITICAL urgency from large extent too.
        area = _num(data.get("affected_area_km2"))
        if agent == "satellite" and area and area > CRITICAL_AREA_KM2:
            urgency = "critical"

        return anomalies, questions, urgency

    # -- terminal states ------------------------------------------------------

    async def on_pipeline_complete(self, event_id: str) -> None:
        """Post a natural closing summary to the room.

        Solution 5: the closing message must reflect the ACTUAL verdict. For a
        neutral verification that found nothing, announcing "Report ready for
        NDMA dispatch" is misleading — we post an honest all-clear instead. The
        verdict is read from the real impact + hazard results (now threaded
        through correctly by Solution 3).
        """
        disaster = self._context.get(event_id, {}).get("disaster", {})
        impact = self._agent_data(event_id, "impact")
        hazard = self._agent_data(event_id, "hazard")
        affected = impact.get("total_affected")
        location = disaster.get("location", "the affected area")

        # Determine the verdict from real downstream data.
        no_impact = bool(impact.get("no_significant_impact")) or (
            affected == 0
        )
        hazard_risk = str(
            hazard.get("flood_risk") or hazard.get("overall_severity") or ""
        ).upper()
        all_clear = no_impact or hazard_risk in ("LOW", "NONE", "UNKNOWN", "MINIMAL")

        if all_clear:
            findings = (
                f"Verification complete for {location}. No significant disaster "
                f"detected — hazard risk {hazard_risk or 'LOW'}, "
                f"{affected if affected is not None else 0} people at risk. "
                "An all-clear situation report has been generated. "
                "No NDMA emergency dispatch required."
            )
            fallback = (
                f"{all_handles_text()} Verification complete for {location}. "
                f"No significant flooding/disaster detected (risk "
                f"{hazard_risk or 'LOW'}). All-clear report generated; no "
                "emergency dispatch required."
            )
        else:
            findings = (
                f"Pipeline complete. {location} response analysis delivered"
                + (f" — {affected} affected" if affected is not None else "")
                + ". Report and map ready for NDMA dispatch."
            )
            fallback = (
                f"{all_handles_text()} Pipeline complete. {location} response "
                "analysis delivered. Report and map ready for NDMA dispatch."
            )

        try:
            summary = await generate_natural_message(
                sender_agent=ORCHESTRATOR_AGENT,
                sender_role=ORCHESTRATOR_ROLE,
                receiver_agent="the response team",
                receiver_handle=all_handles_text(),
                context={"disaster": disaster, "impact": impact, "hazard": hazard},
                findings=findings,
                urgency="normal",
            )
        except Exception:  # noqa: BLE001
            summary = fallback
        room_id = self._room(event_id)
        await send_text_message(summary, mentions=mentions_for_all(), room_id=room_id)
        await send_task_update("Pipeline", "complete", room_id=room_id)

    async def handle_failure(self, event_id: str, agent: str, error: str) -> None:
        """Mark the event failed, log it, and alert the Band room."""
        await update_event_status(event_id, status="failed", step="failed")
        logger.error("event_id=%s: %s failed: %s", event_id, agent, error)

        room_id = self._room(event_id)
        try:
            await send_event(
                "error",
                "Pipeline Failed",
                {"agent": agent, "error": error, "event_id": event_id},
                room_id=room_id,
            )
            await send_task_update("Pipeline", "failed", result=error, room_id=room_id)

            # Natural, urgent alert (still carries agent + event_id for parsing).
            try:
                alert = await generate_natural_message(
                    sender_agent=ORCHESTRATOR_AGENT,
                    sender_role=ORCHESTRATOR_ROLE,
                    receiver_agent="the response team",
                    receiver_handle=all_handles_text(),
                    context={"event_id": event_id},
                    findings=(
                        f"Pipeline disruption — {agent} encountered an issue: {error}. "
                        "Initiating recovery protocol."
                    ),
                    urgency="critical",
                    questions=["Team please stand by."],
                )
            except Exception:  # noqa: BLE001
                alert = (
                    f"⚠️ Pipeline disruption — {agent} encountered an "
                    f"issue: {error}. Initiating recovery protocol. "
                    "Team please stand by."
                )
            if agent not in alert:
                alert = f"{alert} (agent: {agent})"
            if event_id not in alert:
                alert = f"{alert}\nevent_id: {event_id}"
            await send_text_message(
                alert, mentions=mentions_for_all(), room_id=room_id
            )
        except Exception:  # noqa: BLE001 - alerting must never mask the failure
            logger.exception(
                "event_id=%s: failed to post failure alert to Band", event_id
            )

    @staticmethod
    def _is_own_message(parsed: dict) -> bool:
        """True if a stored message was sent by the orchestrator itself.

        CRITICAL (Solution 2): the orchestrator's OWN handoff text says e.g.
        "@hazardmind-impact hazard stage complete". If we counted that as the
        hazard agent's completion, the orchestrator would advance off its own
        echo — firing every downstream handoff within seconds, before any agent
        actually finished, and forwarding empty data. So completion detection
        must consider ONLY messages whose sender is a real pipeline agent.
        """
        sender = str(parsed.get("agent") or "").lower()
        return "orchestrator" in sender

    async def _agent_completed_in_db(self, event_id: str, agent: str) -> bool:
        """True if ``<agent>`` has written its result row to the DB.

        The deterministic autodispatch in each agent writes its DB row even when
        Band's room transcript can't carry a completion signal (REST history is
        empty for per-event rooms). The orchestrator uses this as the reliable
        completion check so it advances and hands off to the next agent. Maps each
        pipeline agent to the table it owns.
        """
        table = {
            "satellite": "satellite_results",
            "hazard": "hazard_zones",
            "impact": "impact_data",
            "report": "final_reports",
        }.get(agent)
        if not table:
            return False
        try:
            from db import get_pool

            pool = await get_pool()
            async with pool.acquire() as conn:
                n = await conn.fetchval(
                    f"SELECT count(*) FROM {table} WHERE event_id = $1", event_id
                )
            return bool(n)
        except Exception:  # noqa: BLE001 - DB check is best-effort
            return False

    async def _agent_completed(self, event_id: str, agent: str) -> bool:
        """True if a message FROM ``<agent>`` reports it complete.

        Reads the inbound_store (populated by the recording adapter). Detects the
        structured completion signal ({"step": "<agent>", "status": "complete"}
        or a flat tail JSON with status=complete) and, as a fallback, the
        plain-text "<agent> complete" marker — but ALWAYS ignores the
        orchestrator's own messages (see _is_own_message) so it never advances
        off its own handoff echo.
        """
        marker = f"{agent} complete".lower()
        # Natural phrasings the LLM-driven agents tend to use instead of the
        # literal "<agent> complete" marker (e.g. "satellite analysis complete").
        natural_markers = (
            f"{agent} analysis complete",
            f"{agent} phase complete",
            f"{agent} processing complete",
            f"{agent} stage complete",
            f"{agent} is complete",
        )
        for parsed in inbound_store.for_event(event_id):
            # Never let the orchestrator's own handoff/echo count as a completion.
            if self._is_own_message(parsed):
                continue

            raw_content = str(parsed.get("content", ""))
            content = raw_content.lower()
            data = parsed.get("data") or {}

            # (1) Authoritative structured signal from the agent.
            if (
                str(data.get("step", "")).lower() == agent
                and str(data.get("status", "")).lower() == "complete"
            ):
                return True
            # (2) Flat tail JSON the agent appends to its room message.
            #
            # CRITICAL: the completion must be ATTRIBUTABLE to THIS agent. We
            # match on an explicit `from`/`agent`/`step` field naming the agent.
            # We must NOT treat an absent/empty tag as a match — otherwise the
            # satellite's completion JSON (which has no `step`/`from`) is counted
            # as hazard's, impact's AND report's completion, so the orchestrator
            # "advances" all three stages in seconds without any agent doing work
            # (the bug seen live: hazard/impact/report never ran, yet the pipeline
            # finished and forwarded the satellite payload as if it were theirs).
            obj = _json_object_from_text(raw_content)
            if isinstance(obj, dict) and str(obj.get("event_id", "")) == event_id:
                tag = str(
                    obj.get("from")
                    or obj.get("agent")
                    or obj.get("step")
                    or ""
                ).lower()
                status_ok = str(obj.get("status", "")).lower() == "complete"
                tag_ok = tag in (agent, f"hazardmind-{agent}")
                if status_ok and tag_ok:
                    return True
            # (3) Plain-text marker fallback (only on a non-orchestrator message).
            if marker in content or any(nm in content for nm in natural_markers):
                return True
        return False

    async def _agent_failed(self, event_id: str, agent: str) -> str | None:
        """Return the error string if ``<agent>`` reported error/failed for this event.

        The pipeline agents post a structured ``{"status": "error"|"failed", ...}``
        payload (and/or a "<agent> ... failed" / "ERROR" line) when they give up —
        e.g. when a sustained internet outage exceeds the download grace budget.
        Detecting it lets monitor_progress abort cleanly instead of waiting forever
        for a completion that will never arrive. Returns the error message, or None.
        """
        for parsed in inbound_store.for_event(event_id):
            raw_content = str(parsed.get("content", ""))
            data = parsed.get("data") or {}
            status = str(data.get("status", "")).lower()
            if status in ("error", "failed"):
                return str(data.get("error") or data.get("message") or "agent reported failure")
            obj = _json_object_from_text(raw_content)
            if (
                isinstance(obj, dict)
                and str(obj.get("event_id", "")) == event_id
                and str(obj.get("status", "")).lower() in ("error", "failed")
            ):
                return str(obj.get("error") or obj.get("message") or "agent reported failure")
        return None


def _num(value):
    """Coerce a value to float, or None if it is not numeric."""
    if value is None or isinstance(value, bool):
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _json_object_from_text(text: str):
    """Extract the first balanced top-level JSON object embedded in text.

    Agents append their structured result after a natural-language message, so
    the JSON starts partway through the content. Scans from each '{' and returns
    the first span that parses as a dict (bracket-balanced, string-aware), or
    None if there is no JSON object.
    """
    import json as _json

    start = text.find("{")
    while start != -1:
        depth = 0
        in_str = False
        escape = False
        for i in range(start, len(text)):
            ch = text[i]
            if in_str:
                if escape:
                    escape = False
                elif ch == "\\":
                    escape = True
                elif ch == '"':
                    in_str = False
                continue
            if ch == '"':
                in_str = True
            elif ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    candidate = text[start : i + 1]
                    try:
                        obj = _json.loads(candidate)
                    except (ValueError, TypeError):
                        break  # malformed; try the next '{'
                    if isinstance(obj, dict):
                        return obj
                    break
        start = text.find("{", start + 1)
    return None
